spring.application.name=vigor
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# SQL init (data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true